services:
 nginx:
  build:
   context: ./requirements/nginx
   args:
    DOMAIN_NAME: ${DOMAIN_NAME}
  image: nginx
  container_name: nginx
  networks:
   - inception
  ports:
   - 443:443
 mariadb:
  build:
   context: ./requirements/mariadb
   environment:
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  image: mariadb
  container_name: mariadb
  networks:
   - inception
  volumes:
   - mariadb-data:/var/lib/mysql
networks:
 inception:
  driver: bridge
volumes:
 mariadb-data:
  driver: local
