services:
 nginx:
  build:
   context: ./requirements/nginx
   args:
    DOMAIN_NAME: ${DOMAIN_NAME}
  image: nginx
  container_name: nginx
  networks:
   - inception
  ports:
   - 443:443
networks:
 inception:
  driver: bridge
volumes:
 mariadb-data:
  driver: local
